import pandas as pd
import numpy as np

prettified_columns = {'Major_category': 'Major Category',
                      'P25th': '25th Percentile Income (US$)',
                      'Median': 'Median Income (US$)',
                      'P75th': '75th Percentile Income (US$)',
                      'norm_risk_rating': 'Risk Rating',
                      'norm_gain_rating': 'Gain Rating',
                      'final_probs': 'Probability of Your Interest'
                      }

final_columns = ['Major',
                 'Major Category',
                 'Unemployment Rate (%)',
                 'Full Time Employment Rate (%)',
                 '25th Percentile Income (US$)',
                 'Median Income (US$)',
                 '75th Percentile Income (US$)']

turkish_majors = {
    "GENERAL AGRICULTURE": "Genel Tarım",
    "AGRICULTURE PRODUCTION AND MANAGEMENT": "Tarım Üretimi ve Yönetimi",
    "AGRICULTURAL ECONOMICS": "Tarım Ekonomisi",
    "ANIMAL SCIENCES": "Hayvan Bilimleri",
    "FOOD SCIENCE": "Gıda Bilimi",
    "PLANT SCIENCE AND AGRONOMY": "Bitki Bilimi ve Tarım Bilimi",
    "SOIL SCIENCE": "Toprak Bilimi",
    "MISCELLANEOUS AGRICULTURE": "Çeşitli Tarım",
    "ENVIRONMENTAL SCIENCE": "Çevre Bilimi",
    "FORESTRY": "Ormancılık",
    "NATURAL RESOURCES MANAGEMENT": "Doğal Kaynaklar Yönetimi",
    "ARCHITECTURE": "Mimarlık",
    "AREA ETHNIC AND CIVILIZATION STUDIES": "Alan, Etnik ve Medeniyet Çalışmaları",
    "COMMUNICATIONS": "İletişim",
    "JOURNALISM": "Gazetecilik",
    "MASS MEDIA": "Kitle İletişimi",
    "ADVERTISING AND PUBLIC RELATIONS": "Reklam ve Halkla İlişkiler",
    "COMMUNICATION TECHNOLOGIES": "İletişim Teknolojileri",
    "COMPUTER AND INFORMATION SYSTEMS": "Bilgisayar ve Bilgi Sistemleri",
    "COMPUTER PROGRAMMING AND DATA PROCESSING": "Bilgisayar Programlama ve Veri İşleme",
    "COMPUTER SCIENCE": "Bilgisayar Bilimi",
    "INFORMATION SCIENCES": "Bilgi Bilimleri",
    "COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY": "Bilgisayar Yönetimi, Yönetimi ve Güvenliği",
    "COMPUTER NETWORKING AND TELECOMMUNICATIONS": "Bilgisayar Ağları ve Telekomünikasyon",
    "GENERAL EDUCATION": "Genel Eğitim",
    "EDUCATIONAL ADMINISTRATION AND SUPERVISION": "Eğitim Yönetimi ve Denetimi",
    "SCHOOL STUDENT COUNSELING": "Okul Öğrenci Danışmanlığı",
    "ELEMENTARY EDUCATION": "İlköğretim",
    "MATHEMATICS TEACHER EDUCATION": "Matematik Öğretmenliği",
    "PHYSICAL AND HEALTH EDUCATION TEACHING": "Beden Eğitimi ve Sağlık Öğretmenliği",
    "EARLY CHILDHOOD EDUCATION": "Erken Çocukluk Eğitimi",
    "SCIENCE AND COMPUTER TEACHER EDUCATION": "Bilim ve Bilgisayar Öğretmenliği",
    "SECONDARY TEACHER EDUCATION": "Ortaöğretim Öğretmenliği",
    "SPECIAL NEEDS EDUCATION": "Özel Eğitim",
    "SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION": "Sosyal Bilimler ve Tarih Öğretmenliği",
    "TEACHER EDUCATION: MULTIPLE LEVELS": "Öğretmen Eğitimi: Çoklu Seviyeler",
    "LANGUAGE AND DRAMA EDUCATION": "Dil ve Drama Eğitimi",
    "ART AND MUSIC EDUCATION": "Sanat ve Müzik Eğitimi",
    "MISCELLANEOUS EDUCATION": "Çeşitli Eğitim",
    "GENERAL ENGINEERING": "Genel Mühendislik",
    "AEROSPACE ENGINEERING": "Havacılık Mühendisliği",
    "BIOLOGICAL ENGINEERING": "Biyolojik Mühendislik",
    "ARCHITECTURAL ENGINEERING": "Mimari Mühendislik",
    "BIOMEDICAL ENGINEERING": "Biyomedikal Mühendislik",
    "CHEMICAL ENGINEERING": "Kimyasal Mühendislik",
    "CIVIL ENGINEERING": "İnşaat Mühendisliği",
    "COMPUTER ENGINEERING": "Bilgisayar Mühendisliği",
    "ELECTRICAL ENGINEERING": "Elektrik Mühendisliği",
    "ENGINEERING MECHANICS PHYSICS AND SCIENCE": "Mühendislik Mekaniği, Fizik ve Bilim",
    "ENVIRONMENTAL ENGINEERING": "Çevre Mühendisliği",
    "GEOLOGICAL AND GEOPHYSICAL ENGINEERING": "Jeoteknik ve Jeofizik Mühendisliği",
    "INDUSTRIAL AND MANUFACTURING ENGINEERING": "Endüstri ve İmalat Mühendisliği",
    "MATERIALS ENGINEERING AND MATERIALS SCIENCE": "Malzeme Mühendisliği ve Malzeme Bilimi",
    "MECHANICAL ENGINEERING": "Makine Mühendisliği",
    "METALLURGICAL ENGINEERING": "Metalurji Mühendisliği",
    "MINING AND MINERAL ENGINEERING": "Madencilik ve Maden Mühendisliği",
    "NAVAL ARCHITECTURE AND MARINE ENGINEERING": "Denizcilik Mimarlığı ve Deniz Mühendisliği",
    "NUCLEAR ENGINEERING": "Nükleer Mühendislik",
    "PETROLEUM ENGINEERING": "Petrol Mühendisliği",
    "MISCELLANEOUS ENGINEERING": "Çeşitli Mühendislik",
    "ENGINEERING TECHNOLOGIES": "Mühendislik Teknolojileri",
    "ENGINEERING AND INDUSTRIAL MANAGEMENT": "Mühendislik ve Endüstriyel Yönetim",
    "ELECTRICAL ENGINEERING TECHNOLOGY": "Elektrik Mühendisliği Teknolojisi",
    "INDUSTRIAL PRODUCTION TECHNOLOGIES": "Endüstriyel Üretim Teknolojileri",
    "MECHANICAL ENGINEERING RELATED TECHNOLOGIES": "Mekanik Mühendisliğe İlişkin Teknolojiler",
    "MISCELLANEOUS ENGINEERING TECHNOLOGIES": "Çeşitli Mühendislik Teknolojileri",
    "LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE": "Dilbilim ve Karşılaştırmalı Dil ve Edebiyat",
    "FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES": "Fransız, Alman, Latince ve Diğer Yaygın Yabancı Dil Çalışmaları",
    "OTHER FOREIGN LANGUAGES": "Diğer Yabancı Diller",
    "COURT REPORTING": "Mahkeme Raporlama",
    "PRE-LAW AND LEGAL STUDIES": "Ön Hukuk ve Hukuk Çalışmaları",
    "ENGLISH LANGUAGE AND LITERATURE": "İngiliz Dili ve Edebiyatı",
    "COMPOSITION AND RHETORIC": "Kompozisyon ve Retorik",
    "LIBERAL ARTS": "Serbest Sanatlar",
    "HUMANITIES": "Beşeri Bilimler",
    "LIBRARY SCIENCE": "Kütüphane Bilimi",
    "BIOLOGY": "Biyoloji",
    "BIOCHEMICAL SCIENCES": "Biyokimyasal Bilimler",
    "BOTANY": "Botanik",
    "MOLECULAR BIOLOGY": "Moleküler Biyoloji",
    "ECOLOGY": "Ekoloji",
    "GENETICS": "Genetik",
    "MICROBIOLOGY": "Mikrobiyoloji",
    "PHARMACOLOGY": "Farmakoloji",
    "PHYSIOLOGY": "Fizyoloji",
    "ZOOLOGY": "Zooloji",
    "NEUROSCIENCE": "Nörobilim",
    "MISCELLANEOUS BIOLOGY": "Çeşitli Biyoloji",
    "MATHEMATICS": "Matematik",
    "APPLIED MATHEMATICS": "Uygulamalı Matematik",
    "STATISTICS AND DECISION SCIENCE": "İstatistik ve Karar Bilimi",
    "MULTI/INTERDISCIPLINARY STUDIES": "Çoklu / Disiplinlerarası Çalışmalar",
    "INTERCULTURAL AND INTERNATIONAL STUDIES": "Kültürlerarası ve Uluslararası Çalışmalar",
    "NUTRITION SCIENCES": "Beslenme Bilimleri",
    "MATHEMATICS AND COMPUTER SCIENCE": "Matematik ve Bilgisayar Bilimleri",
    "COGNITIVE SCIENCE AND BIOPSYCHOLOGY": "Bilişsel Bilim ve Biyopsikoloji",
    "INTERDISCIPLINARY SOCIAL SCIENCES": "Disiplinlerarası Sosyal Bilimler",
    "PHILOSOPHY AND RELIGIOUS STUDIES": "Felsefe ve Din Bilimleri",
    "THEOLOGY AND RELIGIOUS VOCATIONS": "Teoloji ve Dini Meslekler",
    "PHYSICAL SCIENCES": "Fiziksel Bilimler",
    "ASTRONOMY AND ASTROPHYSICS": "Astronomi ve Astrofizik",
    "ATMOSPHERIC SCIENCES AND METEOROLOGY": "Atmosfer Bilimleri ve Meteoroloji",
    "CHEMISTRY": "Kimya",
    "GEOLOGY AND EARTH SCIENCE": "Jeoloji ve Yerbilimleri",
    "GEOSCIENCES": "Jeobİlim",
    "OCEANOGRAPHY": "Oşinografi",
    "PHYSICS": "Fizik",
    "MATERIALS SCIENCE": "Malzeme Bilimi",
    "MULTI-DISCIPLINARY OR GENERAL SCIENCE": "Çok Disiplinli veya Genel Bilim",
    "NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL TECHNOLOGIES": "Nükleer, Endüstriyel Radyoloji ve Biyolojik Teknolojiler",
    "PSYCHOLOGY": "Psikoloji",
    "EDUCATIONAL PSYCHOLOGY": "Eğitim Psikolojisi",
    "CLINICAL PSYCHOLOGY": "Klinik Psikoloji",
    "COUNSELING PSYCHOLOGY": "Danışmanlık Psikolojisi",
    "INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY": "Endüstriyel ve Kurumsal Psikoloji",
    "SOCIAL PSYCHOLOGY": "Sosyal Psikoloji",
    "MISCELLANEOUS PSYCHOLOGY": "Çeşitli Psikoloji",
    "CRIMINAL JUSTICE AND FIRE PROTECTION": "Ceza Adaleti ve Yangın Koruma",
    "PUBLIC ADMINISTRATION": "Kamu Yönetimi",
    "PUBLIC POLICY": "Kamu Politikası",
    "HUMAN SERVICES AND COMMUNITY ORGANIZATION": "İnsan Hizmetleri ve Toplum Örgütlenmesi",
    "SOCIAL WORK": "Sosyal Hizmet",
    "GENERAL SOCIAL SCIENCES": "Genel Sosyal Bilimler",
    "ECONOMICS": "Ekonomi",
    "ANTHROPOLOGY AND ARCHEOLOGY": "Antropoloji ve Arkeoloji",
    "CRIMINOLOGY": "Kriminoloji",
    "GEOGRAPHY": "Coğrafya",
    "INTERNATIONAL RELATIONS": "Uluslararası İlişkiler",
    "POLITICAL SCIENCE AND GOVERNMENT": "Siyaset Bilimi ve Hükümet",
    "SOCIOLOGY": "Sosyoloji",
    "MISCELLANEOUS SOCIAL SCIENCES": "Çeşitli Sosyal Bilimler",
    "FINE ARTS": "Güzel Sanatlar",
    "DRAMA AND THEATER ARTS": "Drama ve Tiyatro Sanatları",
    "MUSIC": "Müzik",
    "VISUAL AND PERFORMING ARTS": "Görsel ve Sahne Sanatları",
    "COMMERCIAL ART AND GRAPHIC DESIGN": "Ticari Sanat ve Grafik Tasarım",
    "FILM VIDEO AND PHOTOGRAPHIC ARTS": "Film, Video ve Fotoğraf Sanatları",
    "ART HISTORY AND CRITICISM": "Sanat Tarihi ve Eleştirisi",
    "STUDIO ARTS": "Stüdyo Sanatları",
    "MISCELLANEOUS FINE ARTS": "Çeşitli Güzel Sanatlar",
    "GENERAL MEDICAL AND HEALTH SERVICES": "Genel Tıbbi ve Sağlık Hizmetleri",
    "COMMUNICATION DISORDERS SCIENCES AND SERVICES": "İletişim Bozuklukları Bilimleri ve Hizmetleri",
    "HEALTH AND MEDICAL ADMINISTRATIVE SERVICES": "Sağlık ve Tıbbi Yönetim Hizmetleri",
    "MEDICAL ASSISTING SERVICES": "Tıbbi Yardımcı Hizmetler",
    "MEDICAL TECHNOLOGIES TECHNICIANS": "Tıbbi Teknolojiler Teknisyenleri",
    "HEALTH AND MEDICAL PREPARATORY PROGRAMS": "Sağlık ve Tıbbi Hazırlık Programları",
    "NURSING": "Hemşirelik",
    "PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION": "Eczacılık, Farmasötik Bilimler ve Yönetim",
    "TREATMENT THERAPY PROFESSIONS": "Tedavi Terapi Meslekleri",
    "COMMUNITY AND PUBLIC HEALTH": "Toplum ve Kamu Sağlığı",
    "MISCELLANEOUS HEALTH MEDICAL PROFESSIONS": "Çeşitli Sağlık Tıbbi Meslekler",
    "GENERAL BUSINESS": "Genel İş",
    "ACCOUNTING": "Muhasebe",
    "ACTUARIAL SCIENCE": "Aktüerya Bilimi",
    "BUSINESS MANAGEMENT AND ADMINISTRATION": "İşletme ve Yönetim",
    "OPERATIONS LOGISTICS AND E-COMMERCE": "Operasyonlar, Lojistik ve E-Ticaret",
    "BUSINESS ECONOMICS": "İş Ekonomisi",
    "MARKETING AND MARKETING RESEARCH": "Pazarlama ve Pazar Araştırmaları",
    "FINANCE": "Finans",
    "HUMAN RESOURCES AND PERSONNEL MANAGEMENT": "İnsan Kaynakları ve Personel Yönetimi",
    "INTERNATIONAL BUSINESS": "Uluslararası İş",
    "HOSPITALITY MANAGEMENT": "Konaklama İşletmeciliği",
    "MANAGEMENT INFORMATION SYSTEMS AND STATISTICS": "Yönetim Bilgi Sistemleri ve İstatistik",
    "MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION": "Çeşitli İş ve Tıbbi Yönetim",
    "HISTORY": "Tarih",
    "UNITED STATES HISTORY": "Amerika Birleşik Devletleri Tarihi"
}


turkish_major_categories = {
    "Agriculture & Natural Resources": "Tarım ve Doğal Kaynaklar",
    "Biology & Life Science": "Biyoloji ve Yaşam Bilimleri",
    "Engineering": "Mühendislik",
    "Humanities & Liberal Arts": "Beşeri ve Liberal Sanatlar",
    "Communications & Journalism": "İletişim ve Gazetecilik",
    "Computers & Mathematics": "Bilgisayarlar ve Matematik",
    "Education": "Eğitim",
    "Law & Public Policy": "Hukuk ve Kamu Politikası",
    "Interdisciplinary": "Disiplinlerarası",
    "Health": "Sağlık",
    "Social Science": "Sosyal Bilimler",
    "Physical Sciences": "Fiziksel Bilimler",
    "Psychology & Social Work": "Psikoloji ve Sosyal Hizmetler",
    "Arts": "Sanatlar",
    "Business": "İşletme"
}


def prettify_final_output(df, pretty_columns, final_columns, num_majors):
    df['Unemployment Rate (%)'] = df.Unemployment_rate * 100
    df['Full Time Employment Rate (%)'] = df.full_time_employment_rate * 100
    df.rename(columns=pretty_columns, inplace=True)
    df["Major"] = df["Major"].map(turkish_majors)
    df["Major Category"] = df["Major Category"].map(turkish_major_categories)
    return df[final_columns].head(num_majors)

def row_to_object(row):
    obj={}
    for column,value in row.items():
        obj[column] = value
    return obj
